# backend/Dockerfile
# FastAPI backend container - environment setup

FROM python:3.11-slim

WORKDIR /app

# ---Dependencies Install -----
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

# Run the FastAPI server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]